### ISSUE TITLE
NoSuchMethodError: com.sun.tools.doclets.formats.html.HtmlDocletWriter

### ISSUE THREAD

**Issue by bagges** [FroMage/jax-doclets#66] opened 2014-12-09 09:26 UTC
I ended up with an NoSuchMethodError on Oracle JDK 8. Is there a workaround or fix available?

Doclet Version: 0.10.1
Javadoc Plugin: 2.10.1
Maven: 3.2.2
Oracle JDK: jdk1.8.0_25

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-site-plugin:3.3:site (default-site) on project xxxxxxxxxxxx: Error during page generation: Error rendering Maven report:
[ERROR] Exit code: 1 - javadoc: error - In doclet class com.lunatech.doclets.jax.jaxrs.JAXRSDoclet,  method start has thrown an exception java.lang.reflect.InvocationTargetException
[ERROR] java.lang.NoSuchMethodError: com.sun.tools.doclets.formats.html.HtmlDocletWriter.<init>(Lcom/sun/tools/doclets/formats/html/ConfigurationImpl;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
[ERROR] at com.lunatech.doclets.jax.jaxrs.writers.JAXRSHtmlDocletWriter.<init>(JAXRSHtmlDocletWriter.java:25)
[ERROR] at com.lunatech.doclets.jax.jaxrs.writers.ResourceWriter.getWriter(ResourceWriter.java:45)
[ERROR] at com.lunatech.doclets.jax.jaxrs.writers.ResourceWriter.<init>(ResourceWriter.java:39)
[ERROR] at com.lunatech.doclets.jax.jaxrs.model.Resource.write(Resource.java:162)
[ERROR] at com.lunatech.doclets.jax.jaxrs.JAXRSDoclet.start(JAXRSDoclet.java:118)
[ERROR] at com.lunatech.doclets.jax.jaxrs.JAXRSDoclet.start(JAXRSDoclet.java:90)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.lang.reflect.Method.invoke(Method.java:483)
[ERROR] at com.sun.tools.javadoc.DocletInvoker.invoke(DocletInvoker.java:310)
[ERROR] at com.sun.tools.javadoc.DocletInvoker.start(DocletInvoker.java:189)
[ERROR] at com.sun.tools.javadoc.Start.parseAndExecute(Start.java:366)
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:219)
[ERROR] at com.sun.tools.javadoc.Start.begin(Start.java:205)
[ERROR] at com.sun.tools.javadoc.Main.execute(Main.java:64)
[ERROR] at com.sun.tools.javadoc.Main.main(Main.java:54)
[ERROR] 
[ERROR] Command line was: "C:\Program Files\Java\jdk1.8.0_25\jre\..\bin\javadoc.exe" @options @packages
```

**Comment by FroMage** [comment] 2014-12-09 10:42
I think this is a dupe of #61.

**Closed as completed** 2021-09-27 07:42 UTC
